islandora_book.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_book_ingest_derivatives:
      type: sequence
    islandora_book_parent_book_solr_field:
      type: string
    islandora_book_metadata_display:
      type: boolean
